compilers:
  - name: "clang"
    version: "3.5"
    cmake_extra_flags: -DUSE_LIB_CXX:BOOL=OFF -DBUILD_SAMPLES:BOOL=ON -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON  -DCOMMIT_SHA=$COMMIT_SHA
  - name: "gcc"
    version: "4.8"
    cmake_extra_flags: -DBUILD_SAMPLES:BOOL=ON -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON  -DCOMMIT_SHA=$COMMIT_SHA
  - name: cppcheck
    compiler_extra_flags: --enable=all -I include --inline-suppr

